export default {
  $schema: "http://json.schemastore.org/prettierrc",
  trailingComma: "es6",
  tabWidth: 2,
  printWidth: 120,
  semi: false,
  singleQuote: true,
  arrowParens: "always",
  importOrder: [
    "<THIRD_PARTY_MODULES>",
    "",
    "^types$",
    "^@/@types/(.*)$",
    "^@/config/(.*)$",
    "^@/lib/(.*)$",
    "^@/controllers/ui/(.*)$",
    "^@/components/(.*)$",
    "",
    "^[./]",
  ],
  importOrderSeparation: false,
  importOrderSortSpecifiers: true,
  importOrderBuiltinModulesToTop: true,
  importOrderParserPlugins: ["typescript", "js", "decorators-legacy"],
  importOrderMergeDuplicateImports: true,
  importOrderCombineTypeAndValueImports: true,
  plugins: ["@ianvs/prettier-plugin-sort-imports"],
};
