name: Test amd Deploy

concurrency:
  group: production
  cancel-in-progress: true

on:
  push:
    branches:
      - main

jobs:
  tests:
    name: Runing Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node & Pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8.14.1
      - uses: actions/setup-node@v3
        with:
          node-version: "20"
          cache: "pnpm"
      - name: Create env file
        run: |
          echo "${{ secrets.ENV_TEST_FILE }}" > .env
      - name: Install dependencies
        run: pnpm i
      - name: Run Jest tests
        env:
          CI: "true"
        run: pnpm test
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    needs: tests
    environment:
      name: production
    steps:
      - uses: actions/checkout@v3
      - name: Setup Pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8.14.1
      - uses: actions/setup-node@v3
        with:
          node-version: "20"
          cache: "pnpm"
      - name: Install dependencies
        run: pnpm install -g serverless && pnpm install
      - name: serverless deploy
        uses: serverless/github-action@v3.2
        with:
          args: -c "serverless deploy --stage production"
          entrypoint: /bin/sh
        env:
          SERVERLESS_ACCESS_KEY: ${{ secrets.SERVERLESS_ACCESS_KEY }}
